const API='https://api.sleeper.app/v1';
const LS='mmDraftAssistant_draftnight_v3';
const OLD_LS='mmDraftAssistant_london_v2';
const BOARD_VERSION='2026-08-24-final-v3';
const TEAM_SEED={
"Allen":{"totalBudget":300,"keepers":[{"name":"Trevor Lawrence","pos":"QB","contract":5},{"name":"Justin Herbert","pos":"QB","contract":5},{"name":"D'Andre Swift","pos":"RB","contract":26},{"name":"Quinshon Judkins","pos":"RB","contract":15},{"name":"Kenneth Gainwell","pos":"RB","contract":5},{"name":"Jaxson S. Njigba","pos":"WR","contract":20},{"name":"Jalen Coker","pos":"WR","contract":5},{"name":"DJ Moore","pos":"WR","contract":5},{"name":"Harold Fannin","pos":"TE","contract":5}]},
"Chris":{"totalBudget":300,"keepers":[{"name":"Dak Prescott","pos":"QB","contract":5},{"name":"James Cook","pos":"RB","contract":34},{"name":"Devonta Smith","pos":"WR","contract":20},{"name":"Jameson Williams","pos":"WR","contract":5},{"name":"Terry McLaurin","pos":"WR","contract":11}]},
"Lukas":{"totalBudget":300,"keepers":[{"name":"Travis Etienne","pos":"RB","contract":15},{"name":"Garret Wilson","pos":"WR","contract":19},{"name":"Sam Laporta","pos":"TE","contract":17}]},
"Trey":{"totalBudget":300,"keepers":[{"name":"Drake Maye","pos":"QB","contract":5},{"name":"Javonte Williams","pos":"RB","contract":15},{"name":"James Conner","pos":"RB","contract":17},{"name":"Chris Olave","pos":"WR","contract":15},{"name":"George Pickens","pos":"WR","contract":9},{"name":"Rome Odunze","pos":"WR","contract":15},{"name":"Juwaan Johnson","pos":"TE","contract":5},{"name":"Jake Ferguson","pos":"TE","contract":23}]},
"Alex":{"totalBudget":310,"keepers":[{"name":"Jaxson Dart","pos":"QB","contract":5},{"name":"Ashton Jeanty","pos":"RB","contract":54},{"name":"Jaylen Warren","pos":"RB","contract":6},{"name":"Alec Pierce","pos":"WR","contract":5},{"name":"Tucker Kraft","pos":"TE","contract":10},{"name":"Colston Loveland","pos":"TE","contract":5}]},
"Danny":{"totalBudget":300,"keepers":[{"name":"Jalen Hurts","pos":"QB","contract":15},{"name":"Jahmyr Gibbs","pos":"RB","contract":115},{"name":"Christian McCaffrey","pos":"RB","contract":69},{"name":"Treveyon Henderson","pos":"RB","contract":15},{"name":"Kyle Monangai","pos":"RB","contract":7},{"name":"Zay Flowers","pos":"WR","contract":5},{"name":"Jaylen Waddle","pos":"WR","contract":15},{"name":"Jordan Addison","pos":"WR","contract":8},{"name":"Tyler Warren","pos":"TE","contract":15}]},
"Nick":{"totalBudget":305,"keepers":[{"name":"Josh Allen","pos":"QB","contract":37},{"name":"Kenneth Walker","pos":"RB","contract":29},{"name":"Omarion Hampton","pos":"RB","contract":23},{"name":"Cam Skattebo","pos":"RB","contract":15},{"name":"Tetairoa McMillan","pos":"WR","contract":22},{"name":"Rashee Rice","pos":"WR","contract":20},{"name":"Emeka Egbuka","pos":"WR","contract":19},{"name":"Christian Watson","pos":"WR","contract":5},{"name":"Trey McBride","pos":"TE","contract":42}]},
"Cade":{"totalBudget":300,"keepers":[{"name":"Jonathan Taylor","pos":"RB","contract":54},{"name":"Derrick Henry","pos":"RB","contract":104},{"name":"Drake London","pos":"WR","contract":37},{"name":"Courtland Sutton","pos":"WR","contract":17},{"name":"George Kittle","pos":"TE","contract":55}]}
};
const ALIAS={"Jaxson S. Njigba":"Jaxon Smith-Njigba","Jamarr Chase":"Ja'Marr Chase","AJ Brown":"A.J. Brown","James Cook":"James Cook III","Kenneth Walker":"Kenneth Walker III","Garret Wilson":"Garrett Wilson","Devonta Smith":"DeVonta Smith","J Croskey-Merrit":"Jacory Croskey-Merritt","Treveyon Henderson":"TreVeyon Henderson","Sam Laporta":"Sam LaPorta","Juan Jennings":"Jauan Jennings","Juwaan Johnson":"Juwan Johnson","Kyle Pitts":"Kyle Pitts Sr.","Harold Fannin":"Harold Fannin Jr.","JK Dobbins":"J.K. Dobbins","Tyrone Tracy":"Tyrone Tracy Jr.","Brian Thomas":"Brian Thomas Jr.","Patrick Mahomes":"Patrick Mahomes II","Deebo Samuel":"Deebo Samuel Sr."};
const DRAIN_PLAN=[
 {name:'Brock Bowers',why:'You already own Loveland + Kraft. Make a TE-needy team spend.'},
 {name:'Lamar Jackson',why:'Dart is viable; buy Lamar only if he stays at or below $20.'},
 {name:'Saquon Barkley',why:'Useful player, but you prefer Chase Brown/Achane/value at similar money.'},
 {name:'Justin Jefferson',why:'You like him only at a big discount; invite someone else to overpay.'},
 {name:'Tyreek Hill',why:'Name-value trap in the current 2026 market.'},
 {name:'Patrick Mahomes II',why:'QB name recognition can drain dollars while you already have Dart.'}
];
const HOLD_PLAN=['Chase Brown',"De'Von Achane",'A.J. Brown','Nico Collins','Breece Hall','Kyren Williams','Ladd McConkey','Tee Higgins'];
let S={board:[],baseBoard:[],teams:{},sales:[],drafted:{},processed:{},mappings:{},league:null,users:[],rosters:[],drafts:[],draft:null,user:null,sleeperTeams:[],timer:null,customBoard:false,settings:{minBid:1,fallback:16,dynMarket:true,dynScarcity:true,dynNeed:true}};
const $=id=>document.getElementById(id), norm=s=>String(s||'').toLowerCase().replace(/[^a-z0-9]/g,''), canon=n=>ALIAS[n]||n, money=n=>Number.isFinite(+n)?'$'+Math.round(+n):'—', clamp=(x,a,b)=>Math.min(b,Math.max(a,x));
function dbg(m,o){$('debug').textContent='['+new Date().toLocaleTimeString()+'] '+m+(o!==undefined?'\n'+JSON.stringify(o,null,2):'')+'\n'+$('debug').textContent.slice(0,9000)}
function toast(t){$('toast').textContent=t;$('toast').classList.add('show');setTimeout(()=>$('toast').classList.remove('show'),4000)}
function csvRows(text){let rows=[],row=[],cell='',q=false;for(let i=0;i<text.length;i++){let c=text[i],n=text[i+1];if(q){if(c==='"'&&n==='"'){cell+='"';i++}else if(c==='"')q=false;else cell+=c}else if(c==='"')q=true;else if(c===','){row.push(cell);cell=''}else if(c==='\n'){row.push(cell);rows.push(row);row=[];cell=''}else if(c!=='\r')cell+=c}row.push(cell);if(row.some(x=>x!==''))rows.push(row);return rows}
function parseBoard(text){let r=csvRows(text),h=r.shift().map(x=>x.trim());return r.filter(x=>x[0]).map(a=>{let o={};h.forEach((k,i)=>o[k]=a[i]??'');for(let k of ['vbd','posRank','fair','hardMax','priority','tier'])o[k]=o[k]===''?null:+o[k];o.avoid=String(o.avoid).toLowerCase()==='true';return o})}
function readSaved(){let cur=null,old=null;try{cur=JSON.parse(localStorage.getItem(LS)||'null')}catch(e){};try{old=JSON.parse(localStorage.getItem(OLD_LS)||'null')}catch(e){};return{cur,old}}
async function loadBoard(){let {cur,old}=readSaved();let r=await fetch('./starter_values.csv?v=3',{cache:'no-store'});S.baseBoard=parseBoard(await r.text());S.board=structuredClone(S.baseBoard);let src=cur||old;if(src){S.mappings=src.mappings||{};S.settings={...S.settings,...(src.settings||{})}}if(cur){S.sales=cur.sales||[];S.processed=cur.processed||{};if(cur.customBoard&&cur.board?.length){S.board=cur.board;S.customBoard=true}}}
function save(){try{localStorage.setItem(LS,JSON.stringify({boardVersion:BOARD_VERSION,customBoard:S.customBoard,board:S.customBoard?S.board:[],sales:S.sales,processed:S.processed,mappings:S.mappings,settings:S.settings}))}catch(e){}}
function initTeams(){S.teams={};for(let [name,d] of Object.entries(TEAM_SEED)){let keepers=structuredClone(d.keepers);S.teams[name]={totalBudget:d.totalBudget,keepers,keeperCost:keepers.reduce((a,p)=>a+(+p.contract||0),0),spent:0,bought:[]}};rebuildDraftedAndSales()}
function rebuildDraftedAndSales(){S.drafted={};for(let [team,t] of Object.entries(S.teams))for(let p of t.keepers)S.drafted[norm(canon(p.name))]={type:'keeper',team,price:p.contract};for(let t of Object.values(S.teams)){t.spent=0;t.bought=[]}for(let s of S.sales){if(s.rosterId){let mapped=teamForRoster(s.rosterId);if(mapped)s.team=mapped}if(s.team&&S.teams[s.team]){if(s.price!=null)S.teams[s.team].spent+=+s.price;S.teams[s.team].bought.push(s)}S.drafted[norm(canon(s.player))]={type:'sale',team:s.team||'Unmapped',price:s.price}}}
function findBoard(name){let q=norm(canon(name));return S.board.find(x=>norm(canon(x.name))===q)||null}
function remaining(team='Alex'){let t=S.teams[team];return t?t.totalBudget-t.keeperCost-t.spent:0}
function rosterSize(){let rp=S.league?.roster_positions;if(Array.isArray(rp)&&rp.length)return rp.filter(x=>!['IR','TAXI'].includes(x)).length;return +S.settings.fallback||16}
function myCount(){return S.teams.Alex.keepers.length+S.teams.Alex.bought.length}
function spots(){return Math.max(0,rosterSize()-myCount())}
function maxAffordable(){return Math.max(0,remaining()-Math.max(0,spots()-1)*(+S.settings.minBid||0))}
function ratios(pos=null){return S.sales.map(s=>{let b=findBoard(s.player);if(!b||s.price==null||!b.fair||b.fair<=0||(pos&&b.pos!==pos))return null;return +s.price/+b.fair}).filter(x=>Number.isFinite(x)&&x>.35&&x<2.5)}
function median(a){if(!a.length)return 1;a=[...a].sort((x,y)=>x-y);let m=Math.floor(a.length/2);return a.length%2?a[m]:(a[m-1]+a[m])/2}
function market(pos){if(!S.settings.dynMarket)return 1;let all=ratios(),pp=ratios(pos),am=all.length>=2?clamp(median(all),.9,1.12):1,pm=pp.length>=2?clamp(median(pp),.9,1.15):am,c=clamp(all.length/10,0,.8);return 1+((.55*am+.45*pm)-1)*c}
function scarcity(r){if(!S.settings.dynScarcity||!r)return 1;let same=S.board.filter(x=>x.pos===r.pos&&(+x.tier||9)<=(+r.tier||9)),avail=same.filter(x=>!S.drafted[norm(canon(x.name))]);if(!same.length)return 1;let gone=1-avail.length/same.length,boost=(+r.tier<=2?.06:+r.tier===3?.035:.015);return 1+gone*boost}
function myPos(){let c={QB:0,RB:0,WR:0,TE:0,K:0,DEF:0};for(let p of [...S.teams.Alex.keepers,...S.teams.Alex.bought]){let pos=p.pos||findBoard(p.player||p.name)?.pos;if(c[pos]!==undefined)c[pos]++}return c}
function posSpend(){let c={QB:0,RB:0,WR:0,TE:0,K:0,DEF:0};for(let s of S.teams.Alex.bought){let p=s.pos||findBoard(s.player)?.pos;if(c[p]!==undefined)c[p]+=+s.price||0}return c}
function need(r){if(!S.settings.dynNeed||!r)return 1;let c=myPos(),sp=posSpend(),p=r.pos;if(p==='WR'){if(c.WR<=1)return 1.06;if(c.WR===2)return 1.05;if(c.WR===3)return 1.03;return sp.WR>=115?.88:.94}if(p==='RB'){if(c.RB<=2)return 1.04;if(c.RB===3)return 1.01;return sp.RB>=45?.90:.95}if(p==='QB')return c.QB>=1?.88:1.05;if(p==='TE')return c.TE>=2?.78:1.02;if(p==='K'||p==='DEF')return .9;return 1}
function dyn(r){if(!r)return null;let hard=Math.min(maxAffordable(),Math.max(0,+r.hardMax||0));if(hard<=0)return{fair:0,hard:0,strong:0,m:market(r.pos),s:scarcity(r),n:need(r)};let m=market(r.pos),s=scarcity(r),n=need(r),f=Math.max(+S.settings.minBid||1,Math.round((+r.fair||0)*m*s*n));f=Math.min(hard,f);let strong=Math.max(+S.settings.minBid||1,Math.round(f*.86));return{fair:f,hard,strong,m,s,n}}
function statusObj(r){let s=S.drafted[norm(canon(r.name))];if(!s)return{label:'Available',cls:'ok'};if(s.type==='keeper'&&s.team==='Alex')return{label:'Your keeper',cls:'bluetxt'};if(s.type==='keeper')return{label:'Kept · '+s.team,cls:'bad'};return{label:'Sold · '+s.team,cls:'bad'}}
function liveMessage(r,d,b){let role=r.role||'';let base=r.note||'';let extra=`Target ${money(d.fair)} · true stop ${money(d.hard)}. Market ${d.m.toFixed(2)}× · scarcity ${d.s.toFixed(2)}× · roster ${d.n.toFixed(2)}×.`;return [role&&('<b>'+role+'</b>.'),base,extra].filter(Boolean).join(' ')}
function renderLive(){let name=$('player').value.trim(),r=findBoard(name),b=+$('bid').value||0;$('pname').textContent=r?.name||name||'Select a player';let rec=$('rec');if(!r){$('badges').innerHTML='<span class="pill">Not on board</span>';rec.className='rec unknown';rec.textContent='NO VALUE';$('fair').textContent=$('hard').textContent='—';$('afford').textContent=money(maxAffordable());$('reason').textContent='Player is not on the current draft-night board.';return}let st=statusObj(r),d=dyn(r),badges=[r.pos+(r.posRank?String(r.posRank):''),'Tier '+(r.tier||'—'),'Priority '+(r.priority||0)+'/5',r.role||''];$('badges').innerHTML=badges.filter(Boolean).map(x=>'<span class="pill">'+x+'</span>').join('');$('fair').textContent=money(d.fair);$('hard').textContent=money(d.hard);$('afford').textContent=money(maxAffordable());if(st.label==='Your keeper'){rec.className='rec keeper';rec.textContent='YOUR KEEPER';$('reason').textContent=r.note||'Already on your roster.';return}if(st.label!=='Available'){rec.className='rec pass';rec.textContent='UNAVAILABLE';$('reason').textContent=st.label+'. '+(r.note||'');return}if(d.hard<=0){rec.className='rec pass';rec.textContent='PASS';$('reason').textContent=r.note||'No bid recommended.';return}if(b<=d.strong){rec.className='rec strong';rec.textContent='🔥 STRONG BUY'}else if(b<=d.fair){rec.className='rec bid';rec.textContent='✅ BID'}else if(b<=d.hard){rec.className='rec caution';rec.textContent='⚠️ BID — CAUTION'}else{rec.className='rec pass';rec.textContent='🛑 PASS'}$('reason').innerHTML=liveMessage(r,d,b)}
function primaryNeed(){let c=myPos(),sp=posSpend();if(c.WR<3||sp.WR<70)return['WR','WR is the biggest spending priority'];if(c.RB<3||sp.RB<25)return['RB','Add one meaningful RB beside Jeanty'];if(c.WR<4)return['WR','A third/fourth useful WR still helps'];return['VALUE','Take the best discount; QB/TE are already covered']}
function renderKPIs(){$('myBudget').textContent=money(remaining());$('budgetSmall').textContent=`${money(S.teams.Alex.totalBudget)} cap · ${money(S.teams.Alex.keeperCost)} keepers · ${money(S.teams.Alex.spent)} auction spent`;$('spotsLeft').textContent=spots();$('spotsSmall').textContent=`${myCount()} rostered / ${rosterSize()} slots`;$('marketFactor').textContent=market(null).toFixed(2)+'×';$('marketSmall').textContent=`${ratios().length} priced sales · target only`;let n=primaryNeed();$('primaryNeed').textContent=n[0];$('needSmall').textContent=n[1]}
function keeperSummary(){let t=S.teams.Alex,n=t.keepers.map(p=>p.name+' '+money(p.contract));$('keeperSummary').innerHTML=`<b>6 keepers · ${money(t.keeperCost)} cost · ${money(remaining())} auction cash</b><br>${n.join(' · ')}`}
function strategySummary(){let c=myPos(),sp=posSpend();$('strategySummary').innerHTML=`<b>Spend shape:</b> WR ~$110–130 · RB ~$35–60 normally (up to $85 for Bijan) · QB $0–16 normally ($20 Lamar ceiling) · TE $0 unless absurd value.<br><span class="muted">Current auction spend: WR ${money(sp.WR)} · RB ${money(sp.RB)} · QB ${money(sp.QB)} · TE ${money(sp.TE)}. Roster: ${c.WR} WR · ${c.RB} RB · ${c.QB} QB · ${c.TE} TE.</span>`}
function nextDrain(){return DRAIN_PLAN.find(x=>{let r=findBoard(x.name);return r&&statusObj(r).label==='Available'})||null}
function nominationSummary(){let d=nextDrain(),holds=HOLD_PLAN.filter(n=>{let r=findBoard(n);return r&&statusObj(r).label==='Available'}).slice(0,5);let html=d?`<div class="nom"><div><b>Nominate now: ${d.name}</b><div class="why">${d.why}</div></div><button class="btn loadNom" data-name="${d.name}">Load</button></div>`:'<div class="okbox">Primary drain nominations are gone. Nominate a player you do not need and preserve your remaining value targets.</div>';if(holds.length)html+=`<div class="small" style="margin-top:8px"><b>Try to keep hidden:</b> ${holds.join(' · ')}</div>`;$('nominationSummary').innerHTML=html;document.querySelectorAll('.loadNom').forEach(b=>b.onclick=()=>{$('player').value=b.dataset.name;$('bid').value=1;renderLive();window.scrollTo({top:0,behavior:'smooth'})})}
function renderTargets(){let q=norm($('search').value),p=$('pos').value,a=$('availability').value;let arr=S.board.filter(r=>(!q||norm(r.name).includes(q))&&(!p||r.pos===p));arr=arr.filter(r=>{let taken=statusObj(r).label!=='Available';return a==='all'||(a==='available'&&!taken)||(a==='drafted'&&taken)});arr.sort((x,y)=>(+y.priority-+x.priority)||((dyn(y)?.fair||0)-(dyn(x)?.fair||0)));$('targetRows').innerHTML=arr.map(r=>{let d=dyn(r),st=statusObj(r);return`<tr><td><b>${r.name}</b><div class="small">${r.note||''}</div></td><td>${r.pos}</td><td>${r.role||''}</td><td class="money">${money(r.fair)}</td><td class="money goldtxt">${money(d?.fair)}</td><td class="money">${money(d?.hard)}</td><td>${'★'.repeat(Math.max(0,Math.min(5,+r.priority||0)))}</td><td class="${st.cls}">${st.label}</td><td><button class="btn load" data-name="${r.name.replaceAll('"','&quot;')}">Load</button></td></tr>`}).join('');document.querySelectorAll('.load').forEach(b=>b.onclick=()=>{$('player').value=b.dataset.name;window.scrollTo({top:0,behavior:'smooth'});renderLive()});$('players').innerHTML=S.board.filter(r=>statusObj(r).label==='Available').sort((a,b)=>(+b.priority-+a.priority)||(+b.fair-+a.fair)).map(r=>`<option value="${r.name.replaceAll('"','&quot;')}"></option>`).join('')}
function teamForRoster(id){let e=Object.entries(S.mappings).find(([,v])=>String(v)===String(id));return e?.[0]||null}
function renderLeague(){$('leagueRows').innerHTML=Object.entries(S.teams).map(([name,t])=>{let opts='<option value="">Unmapped</option>'+S.sleeperTeams.map(st=>`<option value="${st.roster_id}" ${String(S.mappings[name])===String(st.roster_id)?'selected':''}>${st.label}</option>`).join('');return`<tr><td><b>${name}</b>${name==='Alex'?'<div class="goldtxt">MartensiteMafia</div>':''}</td><td><select class="map" data-team="${name}">${opts}</select></td><td>${money(t.totalBudget)}</td><td>${money(t.keeperCost)}</td><td>${money(t.spent)}</td><td class="money ${remaining(name)<50?'bad':'ok'}">${money(remaining(name))}</td><td>${t.bought.length}</td></tr>`}).join('');document.querySelectorAll('.map').forEach(e=>e.onchange=()=>{S.mappings[e.dataset.team]=e.value;rebuildDraftedAndSales();save();renderAll()})}
function renderSales(){$('saleRows').innerHTML=S.sales.length?S.sales.map((s,i)=>`<tr><td>${s.pickNo??i+1}</td><td><b>${s.player}</b></td><td>${s.pos||findBoard(s.player)?.pos||''}</td><td>${s.team||'Unmapped'}</td><td class="money">${s.price==null?'<span class="warn">not exposed</span>':money(s.price)}</td><td>${s.source||'Sleeper'}</td></tr>`).join(''):'<tr><td colspan="6">No auction sales recorded yet.</td></tr>'}
function renderAll(){renderKPIs();keeperSummary();strategySummary();nominationSummary();renderTargets();renderLeague();renderSales();renderLive();save()}
